### ISSUE TITLE
https://firebasestorage.googleapis.com blacklisted

### ISSUE THREAD

**Issue by PAC256-coder** [FirmGuardian/backdoors-and-breaches-pcio#2]
"https://firebasestorage.googleapis.com" it's the cloud storage where the images are stored. Zscaler it's blocking these requests and it's not in my side to whitelist it.

Is there any way to load the .pcio file and change where the pictures point?

**Comment by Ciznit** [comment]
This is an issue with the site, not with this project. You'd have to contact the playingcards.io owner for that.
